merge from https://svn.forge.cnaf.infn.it/svn/storm/backend/branches/BE_1.7 8355:8565 (StoRM 1.8.0 , BE 1.8.0-1)

diff --git a/etc/init.d/storm-backend-server b/etc/init.d/storm-backend-server
--- a/etc/init.d/storm-backend-server
+++ b/etc/init.d/storm-backend-server
@@ -341,6 +341,8 @@ resume () {
 ## start
 
 start () {
+    ulimit -n 4096
+
     local pid
 
         run () { "$@" & : ; }
@@ -402,9 +404,9 @@ start () {
     sleep 5
     test -d /proc/$pid \
         || die 7 "StoRM backend server process unexpectedly died - startup failed."
-    sleep 5
+    sleep 10
     resume \
-        || die 7 "StoRMCommandServer not responding on localhost:$STORM_COMMAND_PORT - startup failed."
+        || (echo 1>&2 "still starting..."; sleep 20; resume) || die 7 "StoRMCommandServer not responding on localhost:$STORM_COMMAND_PORT - startup failed."
 
     # lock subsys (see http://www.redhat.com/magazine/008jun05/departments/tips_tricks/ )
     if test -w /var/lock/subsys; then
@@ -453,18 +455,18 @@ status(){
 
    pslist=$( ps -ef | grep java | grep $NAME | awk '{print $2}' | tr '\n' ' ' | sed -e s/\ $// )
     if [ -n "$pslist" ]; then
-        log_success_msg "StoRM-BE (pid $pslist) is running"
+        log_success_msg "$NAME (pid $pslist) is running"
         return 0
     fi
     if [ -f $PIDFILE ]; then
-        log_warning_msg "StoRM-BE dead but pid file exists"
+        log_warning_msg "$NAME dead but pid file exists"
         return 1
     fi
     if [ -f $LOCKFILE ]; then
-        log_warning_msg "StoRM-BE dead but subsys locked"
+        log_warning_msg "$NAME dead but subsys locked"
         return 2
     fi
-    log_success_msg "StoRM-BE is stopped"
+    log_success_msg "$NAME is stopped"
     return 3
 }
 
@@ -544,7 +546,7 @@ case "$1" in
     suspend) suspend ;;
 	
     # start Picker and XmlRpcServer
-	resume) resume ;;
+    resume) resume ;;
     # query status (only RH systems)
     # FIXME: this cannot work until the BE has a proper UNIX startup...
     # the 'status' function uses 'pidof' to search, and our process has
